/**
 * Supabase TypeScript types
 * 
 * This file is auto-generated by running:
 * npm run typegen
 * 
 * It will be populated when SUPABASE_PROJECT_REF is set and Supabase CLI is available.
 */

// Placeholder types - will be replaced during typegen
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      [key: string]: {
        Row: Record<string, unknown>;
        Insert: Record<string, unknown>;
        Update: Record<string, unknown>;
      };
    };
  };
}

