name: CI

on:
  pull_request:

jobs:
  build-and-test:
    name: Node 22 checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx --yes playwright@1.46.1 install --with-deps

      - name: Typecheck (conditional)
        if: ${{ hashFiles('src/**/*.{ts,tsx,js,jsx}') != '' }}
        run: npm run typecheck

      - name: Lint (conditional)
        if: ${{ hashFiles('eslint.config.*', '.eslintrc.*') != '' }}
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Run Playwright smoke tests
        env:
          CI: true
        run: npx --yes playwright@1.46.1 test --config=playwright.config.ts --reporter=dot
