name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install semantic-release tooling
        run: |
          npm install --no-save \
            semantic-release@24.1.0 \
            @semantic-release/changelog@6.0.3 \
            @semantic-release/commit-analyzer@13.0.0 \
            @semantic-release/git@10.0.1 \
            @semantic-release/github@10.3.3 \
            @semantic-release/npm@11.0.3 \
            @semantic-release/release-notes-generator@14.0.1

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx --no-install semantic-release
